//USER
export const SET_USER = "SET_USER";

// ACCOUNTS

export const FETCH_ACCOUNTS_START = "FETCH_ACCOUNTS_START";
export const FETCH_ACCOUNTS_SUCCESS = "FETCH_ACCOUNTS_SUCCESS";
export const FETCH_ACCOUNTS_FAILED = "FETCH_ACCOUNTS_FAILED";

// PROJECTS

export const FETCH_PROJECTS_START = "FETCH_PROJECTS_START";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAILED = "FETCH_PROJECTS_FAILED";

export const FETCH_PROJECT_START = "FETCH_PROJECT_START";
export const FETCH_PROJECT_SUCCESS = "FETCH_PROJECT_SUCCESS";
export const FETCH_PROJECT_FAILED = "FETCH_PROJECT_FAILED";

export const PROJECTS_LOADING_TRUE = "PROJECTS_LOADING_TRUE";
export const PROJECTS_LOADING_FALSE = "PROJECTS_LOADING_FALSE";

export const CLEAR_PROJECT_IN_STATE = "CLEAR_PROJECT_IN_STATE";

// CONTRACTORS

export const FETCH_CONTRACTORS_START = "FETCH_CONTRACTORS_START";
export const FETCH_CONTRACTORS_SUCCESS = "FETCH_CONTRACTORS_SUCCESS";
export const FETCH_CONTRACTORS_FAILED = "FETCH_CONTRACTORS_FAILED";

export const FETCH_CONTRACTOR_START = "FETCH_CONTRACTOR_START";
export const FETCH_CONTRACTOR_SUCCESS = "FETCH_CONTRACTOR_SUCCESS";
export const FETCH_CONTRACTOR_FAILED = "FETCH_CONTRACTOR_FAILED";

export const CONTRACTORS_LOADING_TRUE = "CONTRACTORS_LOADING_TRUE";
export const CONTRACTORS_LOADING_FALSE = "CONTRACTORS_LOADING_FALSE";

// CATEGORIES

export const FETCH_CATEGORIES_START = "FETCH_CATEGORIES_START";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILED = "FETCH_CATEGORIES_FAILED";

// TRANSACTIONS
export const FETCH_TRANSACTIONS_START = "FETCH_TRANSACTIONS_START";
export const FETCH_TRANSACTIONS_SUCCESS = "FETCH_TRANSACTIONS_SUCCESS";
export const FETCH_TRANSACTIONS_FAILED = "FETCH_TRANSACTIONS_FAILED";

export const CREATE_TRANSACTION_START = "CREATE_TRANSACTION_START";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const CREATE_TRANSACTION_FAILED = "CREATE_TRANSACTION_FAILED";

export const UPDATE_TRANSACTION_START = "UPDATE_TRANSACTION_START";
export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS";
export const UPDATE_TRANSACTION_FAILED = "UPDATE_TRANSACTION_FAILED";

export const DELETE_TRANSACTION_START = "DELETE_TRANSACTION_START";
export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const DELETE_TRANSACTION_FAILED = "DELETE_TRANSACTION_FAILED";

export const CANCEL_TRANSACTION_REPETITION_START =
  "CANCEL_TRANSACTION_REPETITION_START";
export const CANCEL_TRANSACTION_REPETITION_FAIL =
  "CANCEL_TRANSACTION_REPETITION_FAIL";

export const CHANGE_PLANNED_TO_FALSE_START = "CHANGE_PLANNED_TO_FALSE_START";
export const CHANGE_PLANNED_TO_FALSE_FAIL = "CHANGE_PLANNED_TO_FALSE_FAIL";

// FILTERS

export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const UPDATE_PROJECT_FILTERS = "UPDATE_PROJECT_FILTERS";
export const UPDATE_CONTRACTOR_FILTERS = "UPDATE_CONTRACTOR_FILTERS";
//STATE

export const RESET_STATE = "RESET_STATE";
